spring:
  redis:
    # Redis服务器地址
    host: 43.137.19.38
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: Caonima0320,./
  jackson:
    serialization:
      write-dates-as-timestamps: true
